[profile.default]
src = "contracts"
out = "out"
script = "contracts"
libs = ["../../packages/contracts/lib"]
solc = "0.8.27"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]
allow_paths = ["../../packages/contracts/src", "../../packages/contracts/lib"]
remappings = [
    "@nexus/contracts/=../../packages/contracts/src/",
    "forge-std/=../../packages/contracts/lib/forge-std/src/",
    "@openzeppelin/contracts/=../../packages/contracts/lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=../../packages/contracts/lib/openzeppelin-contracts/",
]
