packages:
  - "packages/*"
  - "examples/*"
  - "scripts"
verifyDepsBeforeRun: false
onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
allowBuilds:
  esbuild: set this to true or false
  protobufjs: set this to true or false
