import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { defineGame, t } from "@nexus/core";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { runCodegen } from "../src/lib/codegen.js";

const sample = defineGame({
  name: "uno",
  tables: {
    Player: { id: t.address, roomId: t.uint, isReady: t.bool },
    Hand: { player: t.address, commitment: t.bytes32, count: t.uint8 },
  },
  systems: {
    PlayCardSystem: "./systems/PlayCard.sol",
    DrawSystem: "./systems/Draw.sol",
  },
  economy: { entryFee: { amount: "5", token: "USDC" } },
});

describe("runCodegen", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(resolve(tmpdir(), "nexus-codegen-"));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("writes a manifest.json with the tables + systems from the game", () => {
    const result = runCodegen(sample, dir);

    const manifest = JSON.parse(readFileSync(result.files.manifest, "utf8"));
    expect(manifest.name).toBe("uno");
    expect(manifest.version).toBe(1);
    expect(manifest.tables.map((x: { name: string }) => x.name)).toEqual(["Player", "Hand"]);
    expect(manifest.systems.map((x: { name: string }) => x.name)).toEqual([
      "PlayCardSystem",
      "DrawSystem",
    ]);
    // table ids are deterministic keccak256 hashes
    expect(manifest.tables[0].id).toMatch(/^0x[0-9a-f]{64}$/);
    // fields carry solidity + abi types
    expect(manifest.tables[0].fields).toContainEqual({
      name: "id",
      solidityType: "address",
      abiType: "address",
    });
    expect(manifest.economy.entryFee.amount).toBe("5");
  });

  it("writes a Solidity tables library with the expected library + struct names", () => {
    const result = runCodegen(sample, dir);

    expect(result.files.tablesSol).toMatch(/UnoTables\.sol$/);
    const sol = readFileSync(result.files.tablesSol, "utf8");
    expect(sol).toContain("library UnoTables {");
    expect(sol).toContain("struct PlayerRow {");
    expect(sol).toContain("struct HandRow {");
    expect(sol).toContain("bytes32 internal constant Player_ID =");
    expect(sol).toContain("bytes32 internal constant PlayCardSystem_ID =");
    expect(sol).toContain("address id;");
    expect(sol).toContain("uint8 count;");
    expect(sol).toMatch(/AUTO-GENERATED by @nexus\/core/);
  });

  it("returns the same manifest it writes (no disk round-trip needed)", () => {
    const result = runCodegen(sample, dir);
    const onDisk = JSON.parse(readFileSync(result.files.manifest, "utf8"));
    expect(onDisk).toEqual(result.manifest);
  });
});
